#lang racket
;(require racket/gui)
(require graphics/graphics)

(define horiz-inset 200)
(define vert-inset 35)
(define right-gap 200)
(define bottom-gap 50)
(define horiz 8)
(define vert 8)
(define img-breadth 75)
(define img-length 75)
(define breadth (* horiz img-breadth))
(define length1 (* vert img-length))
(define player "")
(define trash "")

(open-graphics)

(define ideal-board
  (list (list (cons 'B 'rook) (cons 'B 'knight) (cons 'B 'bishop) (cons 'B 'queen) (cons 'B 'king) (cons 'B 'bishop) (cons 'B 'knight) (cons 'B 'rook))
        (list (cons 'B 'pawn) (cons 'B 'pawn)   (cons 'B 'pawn)   (cons 'B 'pawn)  (cons 'B 'pawn) (cons 'B 'pawn)   (cons 'B 'pawn)   (cons 'B 'pawn))
        (list '()            '()               '()               '()              '()             '()               '()               '())
        (list '()            '()               '()               '()              '()             '()               '()               '())
        (list '()            '()               '()               '()              '()             '()               '()               '())
        (list '()            '()               '()               '()              '()             '()               '()                '())
        (list (cons 'W 'pawn) (cons 'W 'pawn)   (cons 'W 'pawn)   (cons 'W 'pawn)  (cons 'W 'pawn) (cons 'W 'pawn)   (cons 'W 'pawn)   (cons 'W 'pawn))
        (list (cons 'W 'rook) (cons 'W 'knight) (cons 'W 'bishop) (cons 'W 'queen) (cons 'W 'king) (cons `W `bishop) (cons `W `knight) (cons 'W 'rook))))
(define board ideal-board)
(define board1 board)

(define (game)
  (define countt 0)
  (set! player 'W)
  (define horiz-inset 100)
  (define vert-inset 40)
  (set! board (list (list `() `() `() `() `() `() `() `())
                    (list `() `() `() `() `() `() `() `())
                    (list `() `() `() `() `() `() `() `())
                    (list `() `() `() `() `() `() `() `())
                    (list `() `() `() `() `() `() `() `())
                    (list `() `() `() `() `() `() `() `())
                    (list `() `() `() `() `() `() `() `())
                    (list `() `() `() `() `() `() `() `())))
  (set! board1 board)
  (define random-board (open-viewport "Test" 800 700))
  (define (db i j)
    (if (= i 9) (set! trash 0)
        (if (= j 9) (db (+ i 1) 1)
            (begin
              ((draw-pixmap random-board) (if (even? (+ i j)) "../Images/White_Tile.png" "../Images/Black_Tile.png")
                                            (make-posn (+ horiz-inset (* 75 (- i 1))) (+ vert-inset (* 75 (- j 1))))
                                            (make-rgb 0 0 0))
              (db i (+ j 1))))))
  
  (db 1 1)
  ; ((draw-pixmap random-board) "Images/Black_Pawn.png" (make-posn 0 0) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/Black_Pawn.png" (make-posn 12 90) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/Black_King.png" (make-posn 12 165) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/Black_Queen.png" (make-posn 12 240) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/Black_Rook.png" (make-posn 12 315) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/Black_Bishop.png" (make-posn 12 380) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/Black_Knight.png" (make-posn 12 465) (make-rgb 0 0 0))
  
  ((draw-pixmap random-board) "Images/White_Pawn.png" (make-posn 710 90) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/White_King.png" (make-posn 710 165) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/White_Queen.png" (make-posn 710 240) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/White_Rook.png" (make-posn 710 315) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/White_Bishop.png" (make-posn 710 380) (make-rgb 0 0 0))
  ((draw-pixmap random-board) "Images/White_Knight.png" (make-posn 710 465) (make-rgb 0 0 0)))

